/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as publicPublicImport } from './routes/(public)/_public'
import { Route as publicPublicSignUpImport } from './routes/(public)/_public.sign-up'
import { Route as publicPublicSignInImport } from './routes/(public)/_public.sign-in'

// Create Virtual Routes

const publicImport = createFileRoute('/(public)')()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/(public)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const publicPublicRoute = publicPublicImport.update({
  id: '/_public',
  getParentRoute: () => publicRoute,
} as any)

const publicPublicSignUpRoute = publicPublicSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicPublicRoute,
} as any)

const publicPublicSignInRoute = publicPublicSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicPublicRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/(public)/_public': {
      id: '/(public)/_public'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicImport
      parentRoute: typeof publicRoute
    }
    '/(public)/_public/sign-in': {
      id: '/(public)/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicPublicSignInImport
      parentRoute: typeof publicPublicImport
    }
    '/(public)/_public/sign-up': {
      id: '/(public)/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicPublicSignUpImport
      parentRoute: typeof publicPublicImport
    }
  }
}

// Create and export the route tree

interface publicPublicRouteChildren {
  publicPublicSignInRoute: typeof publicPublicSignInRoute
  publicPublicSignUpRoute: typeof publicPublicSignUpRoute
}

const publicPublicRouteChildren: publicPublicRouteChildren = {
  publicPublicSignInRoute: publicPublicSignInRoute,
  publicPublicSignUpRoute: publicPublicSignUpRoute,
}

const publicPublicRouteWithChildren = publicPublicRoute._addFileChildren(
  publicPublicRouteChildren,
)

interface publicRouteChildren {
  publicPublicRoute: typeof publicPublicRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicPublicRoute: publicPublicRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof publicPublicRouteWithChildren
  '/sign-in': typeof publicPublicSignInRoute
  '/sign-up': typeof publicPublicSignUpRoute
}

export interface FileRoutesByTo {
  '/': typeof publicPublicRouteWithChildren
  '/sign-in': typeof publicPublicSignInRoute
  '/sign-up': typeof publicPublicSignUpRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_public': typeof publicPublicRouteWithChildren
  '/(public)/_public/sign-in': typeof publicPublicSignInRoute
  '/(public)/_public/sign-up': typeof publicPublicSignUpRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/(public)'
    | '/(public)/_public'
    | '/(public)/_public/sign-in'
    | '/(public)/_public/sign-up'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  publicRoute: typeof publicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  publicRoute: publicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(public)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(public)": {
      "filePath": "(public)",
      "children": [
        "/(public)/_public"
      ]
    },
    "/(public)/_public": {
      "filePath": "(public)/_public.tsx",
      "parent": "/(public)",
      "children": [
        "/(public)/_public/sign-in",
        "/(public)/_public/sign-up"
      ]
    },
    "/(public)/_public/sign-in": {
      "filePath": "(public)/_public.sign-in.tsx",
      "parent": "/(public)/_public"
    },
    "/(public)/_public/sign-up": {
      "filePath": "(public)/_public.sign-up.tsx",
      "parent": "/(public)/_public"
    }
  }
}
ROUTE_MANIFEST_END */
